/**
 * factionBuildMenus.test.ts -- Locks the worker build hotkey grid + the
 * cross-faction consistency contract that prevents Bug F5 from coming back.
 *
 * Bug F5 (audit Fase 3): Randstad had no X-hotkey for a tertiary-resource
 * building. TertiaryResourceSystem expects 2.0 Havermoutmelk/sec per
 * completed `BuildingTypeId.TertiaryResourceBuilding` for FactionId.Randstad
 * (TertiaryResourceSystem.ts:39), but the UI gave Randstad players no way
 * to actually place one. Mission text "vergeet de Havermoutmelk niet"
 * (MissionDefinitions.ts:4294) was unwinnable. Fix: add Randstad's
 * Havermoutmelkbar at hotkey X, tier 2.
 *
 * Brabanders is intentionally exempt — Gezelligheid is generated by
 * GezeligheidSystem via proximity, not buildings (TertiaryResourceSystem
 * .ts:13-14, :87 explicitly skips Brabanders).
 */
import { describe, it, expect } from 'vitest';
import { FACTION_WORKER_BUILDS, FACTION_BUILDING_LABELS } from '../src/ui/factionBuildMenus';
import { BuildingTypeId } from '../src/types/index';
import type { Faction } from '../src/ui/HUD';

const ALL_FACTIONS: readonly Faction[] = ['brabant', 'randstad', 'limburg', 'belgen'];
const NON_BRABANT: readonly Faction[] = ['randstad', 'limburg', 'belgen'];

// ---------------------------------------------------------------------------
// Per-faction hotkey grid coverage
// ---------------------------------------------------------------------------

describe('FACTION_WORKER_BUILDS — hotkey grid coverage', () => {
  for (const faction of ALL_FACTIONS) {
    describe(faction, () => {
      const builds = FACTION_WORKER_BUILDS[faction];

      it('exists and is non-empty', () => {
        expect(builds).toBeDefined();
        expect(builds.length).toBeGreaterThan(0);
      });

      const requiredHotkeys = ['Q', 'E', 'R', 'T', 'F', 'G', 'Z'];
      for (const key of requiredHotkeys) {
        it(`has hotkey ${key}`, () => {
          const entry = builds.find(b => b.hotkey === key);
          expect(entry, `hotkey ${key} missing for faction ${faction}`).toBeDefined();
        });
      }

      it('every entry declares both buildingTypeId and tier', () => {
        for (const entry of builds) {
          expect(entry.buildingTypeId, `${faction}/${entry.hotkey ?? entry.action}: missing buildingTypeId`).toBeDefined();
          expect(entry.tier, `${faction}/${entry.hotkey ?? entry.action}: missing tier`).toBeDefined();
        }
      });

      it('all hotkeys are unique within the faction', () => {
        const keys = builds.map(b => b.hotkey).filter(Boolean);
        expect(new Set(keys).size).toBe(keys.length);
      });
    });
  }
});

// ---------------------------------------------------------------------------
// Cross-faction consistency: same hotkey → same buildingTypeId everywhere
// ---------------------------------------------------------------------------

describe('FACTION_WORKER_BUILDS — cross-faction hotkey↔building consistency', () => {
  const expectedByHotkey: Record<string, BuildingTypeId> = {
    Q: BuildingTypeId.Barracks,
    E: BuildingTypeId.LumberCamp,
    R: BuildingTypeId.Blacksmith,
    T: BuildingTypeId.Housing,
    F: BuildingTypeId.DefenseTower,
    G: BuildingTypeId.FactionSpecial2,
    Z: BuildingTypeId.SiegeWorkshop,
  };

  for (const [hotkey, expectedType] of Object.entries(expectedByHotkey)) {
    for (const faction of ALL_FACTIONS) {
      it(`${faction} hotkey ${hotkey} → BuildingTypeId.${BuildingTypeId[expectedType]}`, () => {
        const entry = FACTION_WORKER_BUILDS[faction].find(b => b.hotkey === hotkey);
        expect(entry?.buildingTypeId).toBe(expectedType);
      });
    }
  }
});

// ---------------------------------------------------------------------------
// Tertiary resource building (X-hotkey) — F5 regression guard
// ---------------------------------------------------------------------------

describe('Tertiary-resource building (X-hotkey)', () => {
  for (const faction of NON_BRABANT) {
    it(`${faction} has X-hotkey for BuildingTypeId.TertiaryResourceBuilding`, () => {
      const entry = FACTION_WORKER_BUILDS[faction].find(b => b.hotkey === 'X');
      expect(
        entry,
        `${faction} must have an X-hotkey building so its tertiary resource can actually be generated`,
      ).toBeDefined();
      expect(entry!.buildingTypeId).toBe(BuildingTypeId.TertiaryResourceBuilding);
    });
  }

  it('Brabanders intentionally has NO X-hotkey (Gezelligheid is proximity-based)', () => {
    const entry = FACTION_WORKER_BUILDS.brabant.find(b => b.hotkey === 'X');
    expect(entry).toBeUndefined();
  });

  it('every X-hotkey entry is tier 2 (matches Limburgers / Belgen pattern)', () => {
    for (const faction of NON_BRABANT) {
      const entry = FACTION_WORKER_BUILDS[faction].find(b => b.hotkey === 'X');
      expect(entry?.tier).toBe(2);
    }
  });
});

// ---------------------------------------------------------------------------
// Faction-specific train-panel labels (sanity)
// ---------------------------------------------------------------------------

describe('FACTION_BUILDING_LABELS — every faction defines all 6 unit labels', () => {
  for (const faction of ALL_FACTIONS) {
    it(`${faction} has worker/infantry/ranged/heavy/siege/support labels`, () => {
      const labels = FACTION_BUILDING_LABELS[faction];
      expect(labels.worker).toBeTruthy();
      expect(labels.infantry).toBeTruthy();
      expect(labels.ranged).toBeTruthy();
      expect(labels.heavy).toBeTruthy();
      expect(labels.siege).toBeTruthy();
      expect(labels.support).toBeTruthy();
    });
  }
});
