/**
 * Reign of Brabant -- Unit Voice Lines
 *
 * Plays faction- and unit-type-specific voice responses when units are
 * selected, moved, ordered to attack, or sent to gather resources.
 * Each action has multiple voice variants picked at random.
 *
 * Voice hierarchy: unit-type-specific → faction-generic fallback.
 *
 * Voice files are generated by scripts/generate_unit_voices.sh via the
 * ElevenLabs TTS API.
 */

import { Howl } from 'howler';
import { audioManager } from './AudioManager';
import { UnitTypeId } from '../types/index';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type VoiceAction = 'select' | 'move' | 'attack' | 'gather';

type UnitTypeName = 'worker' | 'infantry' | 'ranged';

// ---------------------------------------------------------------------------
// Mapping
// ---------------------------------------------------------------------------

const UNIT_TYPE_NAMES: Record<number, UnitTypeName> = {
  [UnitTypeId.Worker]: 'worker',
  [UnitTypeId.Infantry]: 'infantry',
  [UnitTypeId.Ranged]: 'ranged',
};

const FACTION_NAMES: Record<number, string> = {
  0: 'brabanders',
  1: 'randstad',
};

/** Brabanders unit-type display names (for future use). */
const BRABANDERS_NAMES: Record<UnitTypeName, string> = {
  worker: 'boer',
  infantry: 'carnavalvierder',
  ranged: 'kansen',
};

/** Randstad unit-type display names (for future use). */
const RANDSTAD_NAMES: Record<UnitTypeName, string> = {
  worker: 'stagiair',
  infantry: 'manager',
  ranged: 'consultant',
};

const FACTION_UNIT_NAMES: Record<number, Record<UnitTypeName, string>> = {
  0: BRABANDERS_NAMES,
  1: RANDSTAD_NAMES,
};

// ---------------------------------------------------------------------------
// Voice line definitions — per faction, per unit type
// ---------------------------------------------------------------------------

const VOICE_BASE = 'assets/audio/voices/';

function unitLines(faction: string, unitName: string, action: VoiceAction, count: number): string[] {
  const paths: string[] = [];
  for (let i = 1; i <= count; i++) {
    paths.push(`${VOICE_BASE}${faction}/${unitName}/${action}_${i}.mp3`);
  }
  return paths;
}

function genericLines(faction: string, action: VoiceAction, count: number): string[] {
  const paths: string[] = [];
  for (let i = 1; i <= count; i++) {
    paths.push(`${VOICE_BASE}${faction}/${action}_${i}.mp3`);
  }
  return paths;
}

// Per-faction, per-unit-type voice lines (3 variants each)
const UNIT_VOICE_LINES: Record<number, Record<string, Record<VoiceAction, string[]>>> = {
  // Faction 0 — Brabanders
  0: {
    boer: {
      select: unitLines('brabanders', 'boer', 'select', 3),
      move: unitLines('brabanders', 'boer', 'move', 3),
      attack: unitLines('brabanders', 'boer', 'attack', 3),
      gather: unitLines('brabanders', 'boer', 'move', 3), // reuse move for gather
    },
    carnavalvierder: {
      select: unitLines('brabanders', 'carnavalvierder', 'select', 3),
      move: unitLines('brabanders', 'carnavalvierder', 'move', 3),
      attack: unitLines('brabanders', 'carnavalvierder', 'attack', 3),
      gather: unitLines('brabanders', 'carnavalvierder', 'move', 3),
    },
    kansen: {
      select: unitLines('brabanders', 'kansen', 'select', 3),
      move: unitLines('brabanders', 'kansen', 'move', 3),
      attack: unitLines('brabanders', 'kansen', 'attack', 3),
      gather: unitLines('brabanders', 'kansen', 'move', 3),
    },
  },

  // Faction 1 — Randstad
  1: {
    stagiair: {
      select: unitLines('randstad', 'stagiair', 'select', 3),
      move: unitLines('randstad', 'stagiair', 'move', 3),
      attack: unitLines('randstad', 'stagiair', 'attack', 3),
      gather: unitLines('randstad', 'stagiair', 'move', 3),
    },
    manager: {
      select: unitLines('randstad', 'manager', 'select', 3),
      move: unitLines('randstad', 'manager', 'move', 3),
      attack: unitLines('randstad', 'manager', 'attack', 3),
      gather: unitLines('randstad', 'manager', 'move', 3),
    },
    consultant: {
      select: unitLines('randstad', 'consultant', 'select', 3),
      move: unitLines('randstad', 'consultant', 'move', 3),
      attack: unitLines('randstad', 'consultant', 'attack', 3),
      gather: unitLines('randstad', 'consultant', 'move', 3),
    },
  },
};

// Generic faction fallback (used when per-unit files don't exist yet)
const GENERIC_VOICE_LINES: Record<number, Record<VoiceAction, string[]>> = {
  0: {
    select: genericLines('brabanders', 'select', 3),
    move: genericLines('brabanders', 'move', 3),
    attack: genericLines('brabanders', 'attack', 3),
    gather: genericLines('brabanders', 'gather', 3),
  },
  1: {
    select: genericLines('randstad', 'select', 3),
    move: genericLines('randstad', 'move', 3),
    attack: genericLines('randstad', 'attack', 3),
    gather: genericLines('randstad', 'gather', 3),
  },
};

// ---------------------------------------------------------------------------
// Preload tracking — avoid retrying files that don't exist
// ---------------------------------------------------------------------------

const failedPaths = new Set<string>();

// ---------------------------------------------------------------------------
// Cooldown — prevent overlapping voice lines
// ---------------------------------------------------------------------------

let lastVoiceTime = 0;
const VOICE_COOLDOWN = 800; // ms between voice lines

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Play a random voice line for the given faction, unit type, and action.
 *
 * Tries unit-type-specific voices first, falls back to faction-generic.
 * Respects a global cooldown so rapid clicks don't stack voice clips.
 * Ducks the music track while the voice plays for clarity.
 *
 * @param factionId  - 0 = Brabanders, 1 = Randstad
 * @param action     - 'select' | 'move' | 'attack' | 'gather'
 * @param unitTypeId - UnitTypeId enum value (optional, falls back to generic)
 */
export function playUnitVoice(
  factionId: number,
  action: VoiceAction,
  unitTypeId?: number,
): void {
  const now = Date.now();
  if (now - lastVoiceTime < VOICE_COOLDOWN) return;

  // Try unit-type-specific lines first
  let lines: string[] | undefined;

  if (unitTypeId !== undefined) {
    const typeName = UNIT_TYPE_NAMES[unitTypeId];
    if (typeName) {
      const unitNames = FACTION_UNIT_NAMES[factionId];
      if (unitNames) {
        const unitName = unitNames[typeName];
        const factionUnit = UNIT_VOICE_LINES[factionId];
        if (factionUnit && unitName && factionUnit[unitName]) {
          lines = factionUnit[unitName][action];
        }
      }
    }
  }

  // Filter out known-failed paths
  if (lines) {
    lines = lines.filter(p => !failedPaths.has(p));
  }

  // Fallback to generic faction lines
  if (!lines || lines.length === 0) {
    const generic = GENERIC_VOICE_LINES[factionId];
    if (generic) {
      lines = generic[action]?.filter(p => !failedPaths.has(p));
    }
  }

  if (!lines || lines.length === 0) return;

  // Pick a random variant
  const src = lines[Math.floor(Math.random() * lines.length)];

  const sound = new Howl({
    src: [src],
    volume: 0.6,
    onplay: () => {
      audioManager.duckMusic(1500);
    },
    onloaderror: () => {
      // Mark path as failed so we don't retry it
      failedPaths.add(src);
    },
  });

  sound.play();
  lastVoiceTime = now;
}
