/**
 * Reign of Brabant -- Unit Voice Lines
 *
 * Plays faction- and unit-type-specific voice responses when units are
 * selected, moved, ordered to attack, or sent to gather resources.
 * Each action has multiple voice variants picked at random.
 *
 * Voice hierarchy: unit-type-specific → faction-generic fallback.
 * Generic fallback is gender-aware: callers may pass `gender` ('male' /
 * 'female' / 'mixed') so units with a known gender pull from the matching
 * voice-actor pool. When a female pool is empty for a faction, we warn
 * once and fall back to the male pool so audio never goes silent.
 *
 * Voice files are generated by scripts/generate_unit_voices.sh via the
 * ElevenLabs TTS API.
 *
 * Supports all 4 factions: Brabanders, Randstad, Limburgers, Belgen.
 * Supports all unit types: Worker through Hero (UnitTypeId 0-7).
 * Supports voice actions: select, move, attack, gather, death, ability, idle.
 */

import { Howl } from 'howler';
import { audioManager } from './AudioManager';
import { UnitTypeId } from '../types/index';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type VoiceAction = 'select' | 'move' | 'attack' | 'gather' | 'death' | 'ability' | 'idle' | 'ready';

/** Voice-pool gender for fallback selection. */
export type VoiceGender = 'male' | 'female' | 'mixed';

type UnitTypeName = 'worker' | 'infantry' | 'ranged' | 'heavy' | 'siege' | 'support' | 'special' | 'hero';

// ---------------------------------------------------------------------------
// Mapping
// ---------------------------------------------------------------------------

const UNIT_TYPE_NAMES: Record<number, UnitTypeName> = {
  [UnitTypeId.Worker]: 'worker',
  [UnitTypeId.Infantry]: 'infantry',
  [UnitTypeId.Ranged]: 'ranged',
  [UnitTypeId.Heavy]: 'heavy',
  [UnitTypeId.Siege]: 'siege',
  [UnitTypeId.Support]: 'support',
  [UnitTypeId.Special]: 'special',
  [UnitTypeId.Hero]: 'hero',
};

const FACTION_NAMES: Record<number, string> = {
  0: 'brabanders',
  1: 'randstad',
  2: 'limburgers',
  3: 'belgen',
};

/** Brabanders unit-type display names. */
const BRABANDERS_NAMES: Record<UnitTypeName, string> = {
  worker: 'boer',
  infantry: 'carnavalvierder',
  ranged: 'sluiper',
  heavy: 'tractorrijder',
  siege: 'frituurmeester',
  support: 'boerinne',
  special: 'praalwagen',
  hero: 'prins-van-brabant',
};

/** Randstad unit-type display names. */
const RANDSTAD_NAMES: Record<UnitTypeName, string> = {
  worker: 'stagiair',
  infantry: 'manager',
  ranged: 'consultant',
  heavy: 'corporate-advocaat',
  siege: 'vastgoedmakelaar',
  support: 'hr-medewerker',
  special: 'influencer',
  hero: 'de-ceo',
};

/** Limburgers unit-type display names. */
const LIMBURGERS_NAMES: Record<UnitTypeName, string> = {
  worker: 'mijnwerker',
  infantry: 'schutterij',
  ranged: 'vlaaienwerper',
  heavy: 'mergelridder',
  siege: 'kolenbrander',
  support: 'sjpion',
  special: 'mijnrat',
  hero: 'de-mijnbaas',
};

/** Belgen unit-type display names. */
const BELGEN_NAMES: Record<UnitTypeName, string> = {
  worker: 'frietkraamhouder',
  infantry: 'bierbouwer',
  ranged: 'chocolatier',
  heavy: 'frituurridder',
  siege: 'manneken-pis-kanon',
  support: 'wafelzuster',
  special: 'dubbele-spion',
  hero: 'de-frietkoning',
};

const FACTION_UNIT_NAMES: Record<number, Record<UnitTypeName, string>> = {
  0: BRABANDERS_NAMES,
  1: RANDSTAD_NAMES,
  2: LIMBURGERS_NAMES,
  3: BELGEN_NAMES,
};

// ---------------------------------------------------------------------------
// Voice line definitions — per faction, per unit type
// ---------------------------------------------------------------------------

const VOICE_BASE = '/assets/audio/voices/';

function unitLines(faction: string, unitName: string, action: VoiceAction, count: number): string[] {
  const paths: string[] = [];
  for (let i = 1; i <= count; i++) {
    paths.push(`${VOICE_BASE}${faction}/${unitName}/${action}_${i}.mp3`);
  }
  return paths;
}

function genericLines(faction: string, action: VoiceAction, count: number): string[] {
  const paths: string[] = [];
  for (let i = 1; i <= count; i++) {
    paths.push(`${VOICE_BASE}${faction}/${action}_${i}.mp3`);
  }
  return paths;
}

/**
 * Sub-pool generic lines — for additional voice actors mixed into a faction's
 * generic pool (e.g. Sharon Vlaams as 2nd female Belgen voice alongside Petra).
 * Files live in `<faction>/<sub>/<action>_N.mp3` and are appended to the
 * existing pool so the random-select picks them organically.
 */
function subPoolLines(
  faction: string,
  sub: string,
  action: VoiceAction,
  count: number,
): string[] {
  const paths: string[] = [];
  for (let i = 1; i <= count; i++) {
    paths.push(`${VOICE_BASE}${faction}/${sub}/${action}_${i}.mp3`);
  }
  return paths;
}

/**
 * Helper: generates a standard voice line set for a unit.
 * - select/move/attack: 3 variants
 * - death: 2 variants
 * - ability: 2 variants
 * - idle: 2 variants
 * - gather: reuses move lines (existing behaviour)
 */
function standardUnitVoices(
  faction: string,
  unitName: string,
): Record<VoiceAction, string[]> {
  return {
    select: unitLines(faction, unitName, 'select', 3),
    move: unitLines(faction, unitName, 'move', 3),
    attack: unitLines(faction, unitName, 'attack', 3),
    gather: unitLines(faction, unitName, 'move', 3), // reuse move for gather
    death: unitLines(faction, unitName, 'death', 2),
    ability: unitLines(faction, unitName, 'ability', 2),
    idle: unitLines(faction, unitName, 'idle', 2),
    ready: unitLines(faction, unitName, 'idle', 2), // reuse idle as spawn announcement
  };
}

// Per-faction, per-unit-type voice lines
const UNIT_VOICE_LINES: Record<number, Record<string, Record<VoiceAction, string[]>>> = {
  // Faction 0 — Brabanders
  0: {
    boer: standardUnitVoices('brabanders', 'boer'),
    carnavalvierder: standardUnitVoices('brabanders', 'carnavalvierder'),
    sluiper: standardUnitVoices('brabanders', 'sluiper'),
    tractorrijder: standardUnitVoices('brabanders', 'tractorrijder'),
    frituurmeester: standardUnitVoices('brabanders', 'frituurmeester'),
    boerinne: standardUnitVoices('brabanders', 'boerinne'),
    praalwagen: standardUnitVoices('brabanders', 'praalwagen'),
    'prins-van-brabant': standardUnitVoices('brabanders', 'prins-van-brabant'),
  },

  // Faction 1 — Randstad
  1: {
    stagiair: standardUnitVoices('randstad', 'stagiair'),
    manager: standardUnitVoices('randstad', 'manager'),
    consultant: standardUnitVoices('randstad', 'consultant'),
    'corporate-advocaat': standardUnitVoices('randstad', 'corporate-advocaat'),
    vastgoedmakelaar: standardUnitVoices('randstad', 'vastgoedmakelaar'),
    'hr-medewerker': standardUnitVoices('randstad', 'hr-medewerker'),
    influencer: standardUnitVoices('randstad', 'influencer'),
    'de-ceo': standardUnitVoices('randstad', 'de-ceo'),
  },

  // Faction 2 — Limburgers
  2: {
    mijnwerker: standardUnitVoices('limburgers', 'mijnwerker'),
    schutterij: standardUnitVoices('limburgers', 'schutterij'),
    vlaaienwerper: standardUnitVoices('limburgers', 'vlaaienwerper'),
    mergelridder: standardUnitVoices('limburgers', 'mergelridder'),
    kolenbrander: standardUnitVoices('limburgers', 'kolenbrander'),
    sjpion: standardUnitVoices('limburgers', 'sjpion'),
    mijnrat: standardUnitVoices('limburgers', 'mijnrat'),
    'de-mijnbaas': standardUnitVoices('limburgers', 'de-mijnbaas'),
  },

  // Faction 3 — Belgen
  3: {
    frietkraamhouder: standardUnitVoices('belgen', 'frietkraamhouder'),
    bierbouwer: standardUnitVoices('belgen', 'bierbouwer'),
    chocolatier: standardUnitVoices('belgen', 'chocolatier'),
    frituurridder: standardUnitVoices('belgen', 'frituurridder'),
    'manneken-pis-kanon': standardUnitVoices('belgen', 'manneken-pis-kanon'),
    wafelzuster: standardUnitVoices('belgen', 'wafelzuster'),
    'dubbele-spion': standardUnitVoices('belgen', 'dubbele-spion'),
    'de-frietkoning': standardUnitVoices('belgen', 'de-frietkoning'),
  },
};

// ---------------------------------------------------------------------------
// Generic faction fallback (used when per-unit files don't exist yet)
// ---------------------------------------------------------------------------

/**
 * Generic male-pool voice lines per faction. This is the "default" pool that
 * has been recorded already for every faction (Richard / Reinoud-Nick / Serge /
 * Hans-Walter-Petra). Used as the canonical fallback when no female pool is
 * available, and as the active pool for all male and mixed-gender units.
 */
const MALE_GENERIC_VOICE_LINES: Record<number, Record<VoiceAction, string[]>> = {
  0: {
    select: genericLines('brabanders', 'select', 3),
    move: genericLines('brabanders', 'move', 3),
    attack: genericLines('brabanders', 'attack', 3),
    gather: genericLines('brabanders', 'gather', 3),
    death: genericLines('brabanders', 'death', 2),
    ability: genericLines('brabanders', 'ability', 2),
    idle: genericLines('brabanders', 'idle', 2),
    ready: genericLines('brabanders', 'idle', 2),
  },
  1: {
    select: genericLines('randstad', 'select', 3),
    move: genericLines('randstad', 'move', 3),
    attack: genericLines('randstad', 'attack', 3),
    gather: genericLines('randstad', 'gather', 3),
    death: genericLines('randstad', 'death', 2),
    ability: genericLines('randstad', 'ability', 2),
    idle: genericLines('randstad', 'idle', 2),
    ready: genericLines('randstad', 'idle', 2),
  },
  2: {
    // Limburgers male pool: Reinoud (base) + Nick (sub-pool, "transgender Limburger" framing).
    // Random-select rotates organically across actors per call.
    select: [
      ...genericLines('limburgers', 'select', 3),
      ...subPoolLines('limburgers', 'nick', 'select', 3),
    ],
    move: [
      ...genericLines('limburgers', 'move', 3),
      ...subPoolLines('limburgers', 'nick', 'move', 3),
    ],
    attack: [
      ...genericLines('limburgers', 'attack', 3),
      ...subPoolLines('limburgers', 'nick', 'attack', 3),
    ],
    gather: [
      ...genericLines('limburgers', 'gather', 3),
      ...subPoolLines('limburgers', 'nick', 'gather', 3),
    ],
    death: [
      ...genericLines('limburgers', 'death', 2),
      ...subPoolLines('limburgers', 'nick', 'death', 2),
    ],
    ability: [
      ...genericLines('limburgers', 'ability', 2),
      ...subPoolLines('limburgers', 'nick', 'ability', 2),
    ],
    idle: [
      ...genericLines('limburgers', 'idle', 2),
      ...subPoolLines('limburgers', 'nick', 'idle', 2),
    ],
    ready: [
      ...genericLines('limburgers', 'idle', 2),
      ...subPoolLines('limburgers', 'nick', 'ready', 2),
    ],
  },
  3: {
    // Belgen male pool: Hans/Walter (base). Petra/Sharon are female-pool only.
    select: genericLines('belgen', 'select', 3),
    move: genericLines('belgen', 'move', 3),
    attack: genericLines('belgen', 'attack', 3),
    gather: genericLines('belgen', 'gather', 3),
    death: genericLines('belgen', 'death', 2),
    ability: genericLines('belgen', 'ability', 2),
    idle: genericLines('belgen', 'idle', 2),
    ready: genericLines('belgen', 'idle', 2),
  },
};

/**
 * Generic female-pool voice lines per faction. Empty arrays = no female pool
 * recorded yet → fallback to MALE_GENERIC_VOICE_LINES with a console.warn.
 *
 * Currently populated for:
 *   - Limburgers: Nick origineel, "transgender Limburger" framing
 *     (`<base>/limburgers/female/<action>_N.mp3`) — see scripts/generate-limburgers-female-voices.sh
 *   - Belgen: Sharon Vlaams (existing sub-pool, reused as female pool)
 *
 * Brabanders + Randstad: empty for now → male-pool fallback. Future work:
 *   - Brabanders: Emma-natural split (would need separate folder)
 *   - Randstad: female actor TBD
 */
const FEMALE_GENERIC_VOICE_LINES: Record<number, Record<VoiceAction, string[]>> = {
  0: {
    // Brabanders: Emma is part of the existing mixed pool — no separate folder yet.
    select: [],
    move: [],
    attack: [],
    gather: [],
    death: [],
    ability: [],
    idle: [],
    ready: [],
  },
  1: {
    // Randstad: no female pool defined.
    select: [],
    move: [],
    attack: [],
    gather: [],
    death: [],
    ability: [],
    idle: [],
    ready: [],
  },
  2: {
    // Limburgers female: Nick origineel ("transgender Limburger" framing).
    // 24 generic files in <base>/limburgers/female/<action>_N.mp3.
    select: subPoolLines('limburgers', 'female', 'select', 3),
    move: subPoolLines('limburgers', 'female', 'move', 3),
    attack: subPoolLines('limburgers', 'female', 'attack', 3),
    gather: subPoolLines('limburgers', 'female', 'gather', 3),
    death: subPoolLines('limburgers', 'female', 'death', 2),
    ability: subPoolLines('limburgers', 'female', 'ability', 3),
    idle: subPoolLines('limburgers', 'female', 'idle', 2),
    ready: subPoolLines('limburgers', 'female', 'ready', 3),
  },
  3: {
    // Belgen female: Sharon Vlaams sub-pool, reused as the female-only pool.
    select: subPoolLines('belgen', 'sharon', 'select', 3),
    move: subPoolLines('belgen', 'sharon', 'move', 3),
    attack: subPoolLines('belgen', 'sharon', 'attack', 3),
    gather: subPoolLines('belgen', 'sharon', 'gather', 3),
    death: subPoolLines('belgen', 'sharon', 'death', 2),
    ability: subPoolLines('belgen', 'sharon', 'ability', 2),
    idle: subPoolLines('belgen', 'sharon', 'idle', 2),
    ready: subPoolLines('belgen', 'sharon', 'ready', 2),
  },
};

/**
 * Backwards-compat alias: existing call-sites and tests can keep reading
 * GENERIC_VOICE_LINES which now points at the male pool (the historical
 * default). Female callers should pass `gender: 'female'` to playUnitVoice.
 */
const GENERIC_VOICE_LINES = MALE_GENERIC_VOICE_LINES;

/** Tracks which (factionId, action) pairs we've already warned about. */
const fallbackWarned = new Set<string>();

/**
 * Resolve the generic voice-line pool for a faction + gender.
 *
 * - 'male'   → male pool
 * - 'female' → female pool, fall back to male pool with a console.warn if empty
 * - 'mixed' (or undefined) → union of male + female pools (no warn)
 */
function getGenericPool(
  factionId: number,
  action: VoiceAction,
  gender: VoiceGender,
): string[] {
  const male = MALE_GENERIC_VOICE_LINES[factionId]?.[action] ?? [];
  const female = FEMALE_GENERIC_VOICE_LINES[factionId]?.[action] ?? [];

  if (gender === 'male') return male;

  if (gender === 'female') {
    if (female.length === 0) {
      const warnKey = `${factionId}:${action}`;
      if (!fallbackWarned.has(warnKey)) {
        fallbackWarned.add(warnKey);
        console.warn(
          `[UnitVoices] Female pool empty for faction ${factionId} action "${action}" — falling back to male pool.`,
        );
      }
      return male;
    }
    return female;
  }

  // mixed: combine both, drop empties so we don't bias towards a missing pool.
  if (female.length === 0) return male;
  if (male.length === 0) return female;
  return [...male, ...female];
}

// ---------------------------------------------------------------------------
// Easter-egg lines — rare random replacements (Warcraft-style flavour)
// ---------------------------------------------------------------------------

/**
 * Per-faction easter-egg pool. Triggers as a 5% replacement on select/idle/ready
 * actions, voiced by the faction's signature voice (Richard / Reinoud / Serge / Hans).
 * Lines are intentionally distinctive en moeten zelden vallen.
 */
const EASTER_EGG_LINES: Record<number, string[]> = {
  0: [
    '/assets/audio/voices/brabanders/easter-egg/01-vat-pilske.mp3',
    '/assets/audio/voices/brabanders/easter-egg/02-naait-em.mp3',
  ],
  1: [
    '/assets/audio/voices/randstad/easter-egg/01-doe-niet-mee.mp3',
    '/assets/audio/voices/randstad/easter-egg/02-aanhouden.mp3',
  ],
  2: [
    '/assets/audio/voices/limburgers/easter-egg/01-neeje.mp3',
    '/assets/audio/voices/limburgers/easter-egg/02-naar-hoes.mp3',
  ],
  3: [
    '/assets/audio/voices/belgen/easter-egg/01-amai.mp3',
    '/assets/audio/voices/belgen/easter-egg/02-friet.mp3',
  ],
};

const EASTER_EGG_PROBABILITY = 0.05;
const EASTER_EGG_ACTIONS: ReadonlySet<VoiceAction> = new Set(['select', 'idle', 'ready']);

/** Hook for tests: deterministic random source. */
export const __easterEggRng = { random: () => Math.random() };

// ---------------------------------------------------------------------------
// Preload tracking — avoid retrying files that don't exist
// ---------------------------------------------------------------------------

const failedPaths = new Set<string>();

// ---------------------------------------------------------------------------
// Cooldown — prevent overlapping voice lines
// ---------------------------------------------------------------------------

let lastVoiceTime = 0;
const VOICE_COOLDOWN = 800; // ms between voice lines

// ---------------------------------------------------------------------------
// Test-only helpers (named __ to discourage runtime usage)
// ---------------------------------------------------------------------------

/** Reset the fallback-warning de-dup set so tests can re-trigger warns. */
export function __resetFallbackWarnings(): void {
  fallbackWarned.clear();
}

/** Direct access to the gender-aware pool resolver for unit tests. */
export const __getGenericPool = getGenericPool;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Play a random voice line for the given faction, unit type, and action.
 *
 * Tries unit-type-specific voices first, falls back to faction-generic.
 * Respects a global cooldown so rapid clicks don't stack voice clips.
 * Ducks the music track while the voice plays for clarity.
 *
 * @param factionId  - 0 = Brabanders, 1 = Randstad, 2 = Limburgers, 3 = Belgen
 * @param action     - 'select' | 'move' | 'attack' | 'gather' | 'death' | 'ability' | 'idle'
 * @param unitTypeId - UnitTypeId enum value (optional, falls back to generic)
 * @param gender     - 'male' | 'female' | 'mixed' (optional, defaults to 'mixed')
 */
export function playUnitVoice(
  factionId: number,
  action: VoiceAction,
  unitTypeId?: number,
  gender: VoiceGender = 'mixed',
): void {
  const now = Date.now();
  if (now - lastVoiceTime < VOICE_COOLDOWN) return;

  // Easter-egg: 5% kans op signature line (alleen op select/idle/ready)
  if (EASTER_EGG_ACTIONS.has(action) && __easterEggRng.random() < EASTER_EGG_PROBABILITY) {
    const easterPool = EASTER_EGG_LINES[factionId]?.filter(p => !failedPaths.has(p));
    if (easterPool && easterPool.length > 0) {
      const src = easterPool[Math.floor(__easterEggRng.random() * easterPool.length)];
      const sound = new Howl({
        src: [src],
        volume: 0.7,
        onplay: () => audioManager.duckMusic(2000),
        onloaderror: () => failedPaths.add(src),
      });
      sound.play();
      lastVoiceTime = now;
      return;
    }
  }

  // Try unit-type-specific lines first
  let lines: string[] | undefined;

  if (unitTypeId !== undefined) {
    const typeName = UNIT_TYPE_NAMES[unitTypeId];
    if (typeName) {
      const unitNames = FACTION_UNIT_NAMES[factionId];
      if (unitNames) {
        const unitName = unitNames[typeName];
        const factionUnit = UNIT_VOICE_LINES[factionId];
        if (factionUnit && unitName && factionUnit[unitName]) {
          lines = factionUnit[unitName][action];
        }
      }
    }
  }

  // Filter out known-failed paths
  if (lines) {
    lines = lines.filter(p => !failedPaths.has(p));
  }

  // Fallback to gender-aware generic faction pool
  if (!lines || lines.length === 0) {
    lines = getGenericPool(factionId, action, gender).filter(p => !failedPaths.has(p));
  }

  if (!lines || lines.length === 0) return;

  // Pick a random variant
  const src = lines[Math.floor(Math.random() * lines.length)];

  const sound = new Howl({
    src: [src],
    volume: 0.6,
    onplay: () => {
      audioManager.duckMusic(1500);
    },
    onloaderror: () => {
      // Mark path as failed so we don't retry it
      failedPaths.add(src);
    },
  });

  sound.play();
  lastVoiceTime = now;
}

// (FACTION_NAMES and GENERIC_VOICE_LINES are internal — no external consumers.)
